# Generated by Django 5.2 on 2025-05-13 19:13

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension

class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        CreateExtension('postgis'),
    ]
