# Generated by Django 5.2 on 2025-04-28 04:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500)),
                ('blacklisted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'token_blacklist',
                'indexes': [models.Index(fields=['token'], name='token_black_token_6a50c6_idx'), models.Index(fields=['expires_at'], name='token_black_expires_07a99b_idx')],
            },
        ),
    ]
